id: A35939371
title: An Aspiration to Travel to the Hidden Land of Pemokö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:04:22.991294
  last_modified_at: 2022-03-01 05:04:22.991302
